"""rename customer other phone  to other mobile

Revision ID: 211a5e57b99d
Revises: a5b99b23bf59
Create Date: 2026-10-04 20:02:26.176483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211a5e57b99d'
down_revision = 'a5b99b23bf59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_mobile', sa.String(length=10), nullable=True))
        batch_op.drop_column('other_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_phone', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('other_mobile')

    # ### end Alembic commands ###
