"""Changed loan number nullable to true

Revision ID: 344f3f3df47d
Revises: 211a5e57b99d
Create Date: 2026-10-05 15:02:37.528518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344f3f3df47d'
down_revision = '211a5e57b99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('loan_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('loan_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
