"""Added indexing on loan model and payment modelclear

Revision ID: 3b437e573c9b
Revises: 344f3f3df47d
Create Date: 2026-10-06 10:11:35.952098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b437e573c9b'
down_revision = '344f3f3df47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index('ix_loans_company_due_date', ['company_id', 'due_date'], unique=False)
        batch_op.create_index('ix_loans_company_loan_date', ['company_id', 'loan_date'], unique=False)
        batch_op.create_index('ix_loans_company_status', ['company_id', 'status'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_company_payment_date', ['company_id', 'payment_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_company_payment_date')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index('ix_loans_company_status')
        batch_op.drop_index('ix_loans_company_loan_date')
        batch_op.drop_index('ix_loans_company_due_date')

    # ### end Alembic commands ###
