"""updated investor payments table foreighn key

Revision ID: 3c4c37bc72d4
Revises: 3b437e573c9b
Create Date: 2026-10-06 13:43:59.055889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4c37bc72d4'
down_revision = '3b437e573c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('investor_payments_loan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'investors', ['loan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor_payments', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('investor_payments_loan_id_fkey'), 'loans', ['loan_id'], ['id'])

    # ### end Alembic commands ###
