"""rename customer phone to mobile

Revision ID: a5b99b23bf59
Revises: 
Create Date: 2026-10-04 20:00:36.645036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5b99b23bf59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=10), nullable=False))
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.create_index(batch_op.f('ix_customers_mobile'), ['mobile'], unique=True)
        batch_op.drop_column('phone')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('last_login_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_customers_mobile'))
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=True)
        batch_op.drop_column('mobile')

    op.create_table('clients',
    sa.Column('id', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('occupation', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('requests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('alias', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('alias_mobile', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('loan_limit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('outstanding_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('active_loans', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_pkey')),
    sa.UniqueConstraint('mobile', name=op.f('clients_mobile_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
